version: '3.9'


services:
  ansible:
    build:
      context: ..
      dockerfile: docker/Dockerfile.ansible
    volumes:
      - .:/workspace
    working_dir: /workspace

  mongo:
    image: mongo:6.0
    container_name: menhely-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./docker/mongodb-init/demodata.js:/docker-entrypoint-initdb.d/demodata.js:ro
    environment:
      MONGO_INITDB_DATABASE: menhely
    restart: unless-stopped
    networks:
      - shared-net

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: menhely-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongo:27017/menhely
      PORT: 5000
    restart: unless-stopped
    networks:
      - shared-net

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: menhely-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - shared-net

volumes:
  mongo-data:

networks:
  shared-net:
    external: true   
    driver: bridge