
FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Budapest

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-pip \
        sshpass \
        ansible \
        tzdata \
        git \
        curl \
        sudo && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*


RUN groupadd -r ansible && useradd -m -r -g ansible ansible


RUN echo 'ansible:ansible' | chpasswd

RUN echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

USER ansible

WORKDIR /workspace

CMD ["/bin/bash"]
