# 1. Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Csak a package.json-ok másolása a gyorsabb cache-hez
COPY frontend/package*.json ./
RUN npm install

# A teljes frontend kód másolása
COPY frontend/ ./

# Angular build prod környezetben (beleértve az assets mappát is)
RUN npx ng build --configuration production
FROM scratch
COPY --from=build /app/dist/animal-adopt-proj/browser /app
# 2. Serve stage
#FROM nginx:alpine

# Angular build fájlok átmásolása az Nginx default folderbe
# Figyelj: a builded a 'browser' almappában van, ezért azt másoljuk
#COPY --from=build /app/dist/animal-adopt-proj/browser /usr/share/nginx/html

# Saját nginx konfiguráció másolása
#COPY docker/nginx.conf /etc/nginx/conf.d/default.conf

#EXPOSE 80

#CMD ["nginx", "-g", "daemon off;"]
