version: '3.9'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    restart: unless-stopped
    depends_on:
      - prometheus

  graylog:
    image: graylog/graylog:5.1
    container_name: graylog
    ports:
      - "9000:9000"     
      - "12201:12201/udp" 
    environment:
      - GRAYLOG_ROOT_PASSWORD_SHA2=749F09BADE8ACA755660EEB17792DA880218D4FBDC4E25FBEC279D7FE9F65D70
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    restart: unless-stopped
