version: '3.9'

services:
  prometheus:
    build:
      context: ./prometheus
      dockerfile: DockerFile
    ports:
      - "9090:9090"
    networks:
      - shared-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - shared-net
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=adminpassword
    restart: unless-stopped
    depends_on:
      - prometheus

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.20
    environment:
      - discovery.type=single-node
      - cluster.name=graylog
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - shared-net
    volumes:
      - es-data:/usr/share/elasticsearch/data
    restart: unless-stopped


  graylog:
    image: graylog/graylog:4.3
    depends_on:
      - elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201"
      - "12201:12201/udp"
    networks:
      - shared-net
    environment:
      - GRAYLOG_PASSWORD_SECRET=be40c32b4d698f01d8d4c2cab3b3251e7bb53f1cdb7c14447c237a7fb51f0601
      - GRAYLOG_ROOT_PASSWORD_SHA256=749f09bade8aca755660eeb17792da880218d4fbdc4e25fbec279d7fe9f65d70
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
      - GRAYLOG_MONGODB_URI=mongodb://mongo:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    restart: unless-stopped

volumes:
  es-data:

networks:
  shared-net:
    external: true