# 1. Build stage
FROM node:20-alpine AS build

WORKDIR /app

# Csak a package.json-ok a gyorsabb cache-hez
COPY backend/package*.json ./
RUN npm install
RUN npm install -g typescript
# A teljes backend kód másolása
COPY backend/ ./

# TypeScript fordítása
RUN npx tsc

# 2. Run stage
FROM node:20-alpine

WORKDIR /app

# Node dependencies
COPY backend/package*.json ./
RUN npm install --only=production

# Build fájlok átmásolása
COPY --from=build /app/dist ./dist

# A belépő fájl a dist-ben
CMD ["node", "dist/index.js"]


EXPOSE 5000
