server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Angular SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # statikus fájlok (assets, favicon, js, css)
    location /assets/ {
        root /usr/share/nginx/html;
    }

    error_page 404 /index.html;
}
