pipeline {
    agent any

    environment {
        BACKEND_DIR = "backend"
        FRONTEND_DIR = "frontend"
        DOCKERHUB_USER = "szlly"
        APP_NAME_BACKEND = "animal-backend"
        APP_NAME_FRONTEND = "animal-frontend"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Backend - Install & Build') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                dir("${BACKEND_DIR}") {
                    sh 'npm install'
                    sh './node_modules/.bin/tsc'
                }
            }
        }

        stage('Frontend - Install & Build') {
            agent {
                docker {
                    image 'node:20-alpine'
                    args '-v /var/run/docker.sock:/var/run/docker.sock'
                }
            }
            steps {
                dir("${FRONTEND_DIR}") {
                    sh 'npm install'
                    sh './node_modules/.bin/ng build --configuration production'
                }
            }
        }

        stage('Docker Build Images') {
            steps {
                sh "docker build -t ${DOCKERHUB_USER}/${APP_NAME_BACKEND}:latest -f docker/Dockerfile.backend ."
                sh "docker build -t ${DOCKERHUB_USER}/${APP_NAME_FRONTEND}:latest -f docker/Dockerfile.frontend ."
            }
        }

    }
}
