FROM prom/prometheus:latest

# Copy config from host into container
COPY config/prometheus.yml /etc/prometheus/prometheus.yml

# Expose port
EXPOSE 9090

# Default command
CMD ["--config.file=/etc/prometheus/prometheus.yml"]
